pipeline {
    agent {
        node {
            label 'jenkins-slave3.yvu.ch'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo Build'
                sh 'cd Gadgeothek; ./gradlew build'
            }
        }
        stage('End2End Tests') {
            steps {
                sh 'echo End2End Tests'
                sh 'cd Gadgeothek; ./gradlew connectedAndroidTest'
            }
        }
        stage('Publish') {
            steps {
                sh 'echo Publish'
            }
        }
    }
    post {
        success {
            archiveArtifacts '**/outputs/apk/*.apk'
        }
    }
}