pipeline {
    agent {
        node {
            label 'jenkins-slave4.yvu.ch'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo Build'
                sh '(cd Gadgeothek; ./gradlew build)'
            }
            post {
                success {
                    archiveArtifacts '**/outputs/apk/*.apk'
                }
            }
        }
        stage('Unit Tests') {
            steps {
                sh 'echo Unit Tests'
                sh '(cd Gadgeothek; ./gradlew test)'
            }
        }
        /*
        stage('End2End Tests') {
            steps {
                sh 'echo End2End Tests'
                sh '(cd Gadgeothek; ./gradlew connectedAndroidTest)'
            }
        }
        */

        stage('Package') {
            steps {
                sh './Gadgeothek/scripts/package-android.sh'
            }
            post {
                success { archiveArtifacts 'Gadgeothek/app/build/outputs/apk/Gadgeothek.apk' }
            }
        }
        stage('Publish') {
            steps {
                sh 'echo Publish'
            }
        }
    }
    post {
        always {
            junit allowEmptyResults: true, testResults: '**/build/test-results/testDemoDebugUnitTest/*.xml'
            sh '(cd Gadgeothek; ./gradlew storeResults)'

            cleanWs()
        }
    }
}